version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: contract-monitor-db
    environment:
      POSTGRES_DB: contractmonitordb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: